import type { Metadata } from "next";

import "./globals.css";
import { IBM_Plex_Sans, Source_Sans_3, Geist } from "next/font/google";
import { cn } from "@/lib/utils";

const sourceSans3Heading = Source_Sans_3({subsets:['latin'],variable:'--font-heading'});

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={cn("h-full", "antialiased", "font-sans", geist.variable, sourceSans3Heading.variable)}>
      <body className="min-h-full flex flex-col">
        <h1>Navbar</h1>
        {children}
        <h2>footer</h2>
      </body>
    </html>
  );
}
